# This is a basic workflow that is manually triggered

name: Run a tag

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Which tag would you like to run?'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  run_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Install project dependencies
        uses: docker://dataformco/dataform:1.17.2
        with:
          args: install
      - name: Decrypt Dataform credentials
        run: s./decrypt_credentials.sh
        env:
          DATAFORM_CREDS_GPG_PASSPHRASE: ${{ secrets.DATAFORM_CREDS_GPG_PASSPHRASE }}
      - name: Create a run with all actions
        uses: docker://dataformco/dataform:1.17.2
        with:
          args: run ${{ github.event.inputs.name }}
